modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Ranks/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbranks"
version = "${version}"
displayName = "FTB Ranks"
authors = "LatvianModder"
description = '''
A simple mod that lets you create ranks for players, similar to Discord roles, and manage permissions for them
'''

[[dependencies.ftbranks]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "architectury"
mandatory = true
versionRange = "[1.17.20,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1605.3.1-build.56,)"
ordering = "AFTER"
side = "BOTH"