modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Ranks/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbranks"
version = "${version}"
displayName = "FTB Ranks"
authors = "LatvianModder"
description = '''
A simple mod that lets you create ranks for players, similar to Discord roles, and manage permissions for them
'''

[[dependencies.ftbranks]]
modId = "forge"
mandatory = true
versionRange = "[40.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "architectury"
mandatory = true
versionRange = "[3.2.52,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbranks]]
modId = "ftblibrary"
mandatory = true
versionRange = "[1802.3.8-build.161,)"
ordering = "AFTER"
side = "CLIENT"