org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_id=ftbranks
readable_name=FTB Ranks
archives_base_name=ftb-ranks
maven_group=dev.ftb.mods

# MC
minecraft_version=26.2
supported_minecraft_versions=26.2,26.2.1,26.2.2
minecraft_version_range_maven=[26.2,27)
minecraft_version_range_semver=>=26.2.0

mod_version=3
mod_author=FTB Team

# Deps
neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2.0.7-beta,27)
neoforge_loader_version=4

fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2
fabric_api_version_range=>=0.144.0+26.2

ftb_library_version=26.2.0.8-SNAPSHOT
ftb_library_version_range_semver=>=26.2.0.8
ftb_library_version_range_maven=[26.2.0.8,27)

curseforge_id_forge=314905
curseforge_id_fabric=472659
