modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Ranks/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbranks"
version = "${file.jarVersion}"
displayName = "FTB Ranks"
authors = "LatvianModder"
description = '''
A simple mod that lets you create ranks for players, similar to Discord roles, and manage permissions for them
'''

[[dependencies.ftbranks]]
    modId="forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
    side="BOTH"

[[dependencies.ftbranks]]
    modId="minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
    side="BOTH"